### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by playcodersf** [TharunDharmaraj/Wallpaperly-1k-HD-Android-Wallpapers#1]
app is crashing every time i click on a wallpaper

**Comment by TharunDharmaraj** [comment]
> app is crashing every time i click on a wallpaper

From which fragment does it happens and does it happen for popular tab and categories tab? Also please tell me the version of android that you are using.

**Comment by TharunDharmaraj** [comment]
Please make sure that you have granted storage permissions to the app.

**Comment by playcodersf** [comment]
Give me your mail ID i couldn't reply

**Comment by TharunDharmaraj** [comment]
Sure, tharundharmaraj@gmail.com

**Comment by TharunDharmaraj** [comment]
Done
