### ISSUE TITLE
App crashes in android 11

### ISSUE THREAD

**Issue by devloperyogesh** [TharunDharmaraj/Wallpaperly-1k-HD-Android-Wallpapers#4]
![Screenshot 2023-06-21 125913](https://github.com/TharunDharmaraj/Wallpaperly-1k-HD-Android-Wallpapers/assets/137510518/b2ee1360-23c3-48ac-b2a8-8dd50552f37f)

this app is not stable yet it gives error .

**Comment by TharunDharmaraj** [comment]
Sure, I'll look into it

**Comment by TharunDharmaraj** [comment]
Can you send me the full error?

**Comment by devloperyogesh** [comment]
If you hava Android 11 phone then run it . You will get error.

Or Tell me which is the full error to be sent.

If possible give me your Gmail so , i will send it on there .

**Comment by TharunDharmaraj** [comment]
tharundharmaraj@gmail.com
